### ISSUE TITLE
It just opens Notepad with output from Strings on how to call it

### ISSUE THREAD

**Issue by SamSirry** [STaRDoGG/geekdrop-peek#2]
Done the installation as usual, on Windows7, in a directory and drive other than C: (where Windows is).
When I try to peek into a file, after a second of waiting, I get Notepad open with output from the Strings program detailing how to use it, as if the parameters passed to it were incorrect.

And by the way, the first time I ran it, the output (in Notepad) said that I must accept the EULA of Strings, so I ran it manually to get the EULA dialog and accept it. I know that you can override this by setting a registry value.

**Comment by jscottelblein** [comment]
Thanks for reporting, I'll check it out. I also noticed the EULA issue when I ran it on a new machine. That's an easy fix to add in. I've got a ton of new stuff I've already added locally, and plan to add; I'll add that in as well. It's going to be a while though since I have a lot of other projects going on right now.

**Comment by SamSirry** [comment]
Thank you for following up :)
Here is the registry setting, just to save you a couple of minutes finding it:

`Windows Registry Editor Version 5.00`

`[HKEY_CURRENT_USER\Software\Sysinternals\Strings]`
` "EulaAccepted"=dword:00000001`

**Comment by jscottelblein** [comment]
Much appreciated. =)

I may have to show that EULA upon first load anyway, just to satisfy any potential gripes by the Strings author. I'll probably show it in it's own window on first run with a note to restart GD Peek, then add the regkey so it no longer shows on subsequent runs.

Down the road when I have more time I'll add in my own code to extract the strings so no external program is necessary.

**Comment by jscottelblein** [comment]
Fixed in next release
